Desktop version of my portfolio
NoelLincoln/myportfolio pull request #4
Opened 2023-07-13 23:29 UTC by NoelLincoln

**Hello 👋**
I have finished the desktop design as required  : 
- using flexbox layout 
- replicating the figma design as much as possible
- using percentages instead of absolute value like pixels

2023-07-13 23:53 UTC, zieeco requested changes
Hi @NoelLincoln,

<img height="220" src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 23:53 UTC, zieeco commented on style.css
> +  }
- Hey, please, let's control the extra white space here by removing it. see the image below:

![image](https://github.com/NoelLincoln/myportfolio/assets/59397159/bf04a82b-16e6-4be0-a75b-47f15ae09e2f)

2023-07-13 23:53 UTC, zieeco commented on style.css
> +    text-decoration: none !important;
- Hey, let's try to add the rule without using the !important rule as a guide in the microverse list of the [HTML & CSS requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md). Plese, kindly remove it.

2023-07-13 23:53 UTC, zieeco commented on style.css
> +  p,
-- Hey, let's improve the font sizes of the elements in the desktop version as yours is still not close. below is an example of the paragraph in the headline section. please, improve on all the font sizes to make your design better:


![image](https://github.com/NoelLincoln/myportfolio/assets/59397159/61da0900-cfed-4b11-a933-d71e99751b33)

2023-07-14 08:08 UTC, Ibizugbe requested changes
Hi @NoelLincoln 👋👋, 

![tryagain](https://github.com/NoelLincoln/myportfolio/assets/64643995/27ba3b7e-ca20-4454-b370-bbffc7d16a3e)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅

- [x] Font-sizes has been improved as requested by the previous reviewer👍.
- [x] White space has been removed as requested by the previous reviewer👍.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIIONAL] Nice job so far👍. there are still some improvements that can be added to your project to make it match the design😉 I think the previous reviewer probably forgot to point them out.
- [OPTIONAL] for example, the texts in the project cards on your desktop are going out of position, both on mobile and desktop.
yours
<img width="553" alt="image" src="https://github.com/NoelLincoln/myportfolio/assets/64643995/cde57d78-522d-42ea-b5c6-3a7d7d98c6bf">

design
<img width="444" alt="image" src="https://github.com/NoelLincoln/myportfolio/assets/64643995/530ff858-2d07-44b2-8f8c-909004f170f4">

- [OPTIONAL]Also, Kindly note that the reverse properties in your cards only apply to desktop screens and not mobile screens🥲.
Yours 
<img width="470" alt="image" src="https://github.com/NoelLincoln/myportfolio/assets/64643995/e2056bb2-ecf7-4331-bef3-6f69feb0d27a">

design
<img width="325" alt="image" src="https://github.com/NoelLincoln/myportfolio/assets/64643995/34059e0c-4c0e-4fc3-995f-513476ff8980">

Note that on mobile, the image has to always come first, on like in the desktop screen😉.

- [OPTIONAL] In summary, Kindly compare your project to the design and ensure everything looks similar as  adhering strictly to a design is a great professional skill in the job market and it makes you more attractive to employers😉.


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 08:08 UTC, Ibizugbe commented on style.css
> +    text-decoration: none !important;
Just as the previous reviewer has requested, Kindly take away every `!important` rule in your project as this is part of the  [HTML & CSS requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) requirements👍.

<img width="443" alt="image" src="https://github.com/NoelLincoln/myportfolio/assets/64643995/a5016ace-e9ac-4303-b030-ab0ad12adccd">

2023-07-14 10:17 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @NoelLincoln     , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/3Hb1STCbFroaErsYT0/giphy.gif"/>

## Highlights :fire: 
- All requested changes implemented :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 10:25 UTC, merged